# Change these first
owner: Formplus # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Template Page
    url: https://formpl.us/templates

# status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
#   cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://www.formpl.us/static/images/logo/formplus-logo.png
  name: Formplus
  introTitle: "Online & Offline Data Collection Tool | Formplus"
  introMessage: This is a status page to monitor availability of resources 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
